### ISSUE TITLE
tenant created on runtime error in tenant_create.py

### ISSUE THREAD

**Issue by clintcarr** [qlik-oss/qlik-cloud-examples#25]
## 🐛 Bug report

When creating a tenant using the python SDK (tenant_create.py) with an invalid source-tenant-admin email address the tenant gets created but the code fails with: RuntimeError: No user with email 'cac@qlik.com' exists in the tenant 'https://1zmwfnaj282qgxv.ap.qlikcloud.com'.

I understand I can create an interactive user for this tenant.  However the code shouldn't create a tenant if there is a runtime error.

### Steps to Reproduce

1. Create a tenant with "tenant_create.py"
2. Use an invalid email address as a parameter

### Expected behavior

If the code has an interactive failure it should not execute.

### Actual behavior

A tenant is created.

### Versions

- Python: 3.8

### Additional context

(Add any other context, link to demo or screenshots about the issue.)
<img width="705" alt="Screen Shot 2022-10-19 at 1 44 11 pm" src="https://user-images.githubusercontent.com/23019389/196585354-f9f66ccf-7e5a-40fb-a85a-84cd8007e063.png">

**Comment by withdave** [comment]
Thanks @clintcarr!

Following up as we spoke about this a few weeks ago - in production these would need proper error handling and likely different logic to fit a specific use case...but you raise a good point.

The failure step is the lookup of the user subject from the source tenant. It would make sense to run this step before the tenant creation since having the subject is a dependency. This script is written the way it is because in the tutorial series the addition of an interactive `Qlik Account` login is an optional step completed after the tenant creation.

I'll take note for a future revision of the docs & scripts and mark this as an enhancement, and of course please feel free to send a PR if you feel so inclined!

**Comment by withdave** [comment]
Closing as this enhancement isn't currently planned
